server:
  port: 9200
spring:
  application:
    name: service-feign
  pid:
    file: ./service-feign.pid
info:
  app:
    name: service-feign
    version: 1.0.0
eureka:
  instance:
    lease-renewal-interval-in-seconds: 5
    lease-expiration-duration-in-seconds: 15
    prefer-ip-address: true
    instance-id: ${spring.cloud.client.ip-address}:${server.port}
  client:
    serviceUrl:
      defaultZone: http://eureka.xucongblog.com:9000/eureka/
    registry-fetch-interval-seconds: 5
feign:
  hystrix:
    enabled: true
ribbon:
  MaxAutoRetries: 2
  MaxAutoRetriesNextServer: 2
  OkToRetryOnAllOperations: false
management:
  endpoint:
    health:
      show-details: ALWAYS
    shutdown:
      enabled: true
    pause:
      enabled: true
  endpoints:
    web:
      exposure:
        include: "*"