server:
  port: 9400
spring:
  application:
    name: monitor-admin
  pid:
    file: ./monitor-admin.pid
  security:
    user:
      name: xucong
      password: xc886696
  boot:
    admin:
      notify:
        mail:
          from: xcong94@163.com
          to: xcong94@163.com
  mail:
    host: smtp.163.com
    username: xcong94@163.com
    password: Xcong886696
    properties:
      mail.debug: false
      mail.smtp.auth: true
      mail.smtp.port: 587
      mail.smtp.ssl.enable: true
eureka:
  instance:
    health-check-url-path: /actuator/health
    prefer-ip-address: true
    instance-id: ${spring.cloud.client.ip-address}:${server.port}
    metadata-map:
      startup: ${random.int}    #needed to trigger info and endpoint update after restart
  client:
    registry-fetch-interval-seconds: 5
    serviceUrl:
      defaultZone: http://localhost:9000/eureka/
    register-with-eureka: false

management:
  endpoints:
    web:
      exposure:
        include: "*"
  endpoint:
    health:
      show-details: ALWAYS
