eureka:
  instance:
    lease-renewal-interval-in-seconds: 30
    lease-expiration-duration-in-seconds: 90
    prefer-ip-address: true
  client:
    serviceUrl:
      defaultZone: http://s1:9000/eureka/,http://s2:9001/eureka/,http://s3:9003/eureka/
server:
  port: 9300
spring:
  application:
    name: service-zuul
zuul:
  routes:
    api:
      path: /api/**
      serviceId: service-feign
info:
  app:
    name: service-zuul
    version: 1.0.0
management:
  endpoints:
    web:
      exposure:
        include: "*"