server:
  port: 9002

eureka:
  instance:
    hostname: s3
    prefer-ip-address: true
  server:
    eviction-interval-timer-in-ms: 20000
  client:
    registerWithEureka: true
    fetchRegistry: true
    serviceUrl:
      defaultZone: http://s1:9000/eureka/,http://s2:9001/eureka/,http://s3:9002/eureka/

spring:
  application:
    name: eurka-server