server:
  port: 9000
eureka:
  instance:
    hostname: s1
    prefer-ip-address: true
  server:
    eviction-interval-timer-in-ms: 20000
    response-cache-auto-expiration-in-seconds: 30
  client:
    registerWithEureka: false
    fetchRegistry: false
    serviceUrl:
      defaultZone: http://s1:9000/eureka/,http://s2:9001/eureka/
spring:
  application:
    name: eurka-server