
eureka:
  instance:
    lease-renewal-interval-in-seconds: 30
    lease-expiration-duration-in-seconds: 90
    prefer-ip-address: true
  client:
    serviceUrl:
      defaultZone: http://s1:9000/eureka/,http://s2:9001/eureka/,http://s3:9003/eureka/
server:
  port: 9201
spring:
  application:
    name: service-feign
info:
  app:
    name: service-feign
    version: 1.0.0
feign:
  hystrix:
    enabled: true
management:
  endpoints:
    web:
      exposure:
        include: "*"